name: Budapest vízállás

on:
  workflow_dispatch:
  schedule:
    - cron: '5 * * * *'

permissions:
  contents: write

jobs:
  run-r-script:
    runs-on: ubuntu-latest

    steps:
      - name: Repository letöltése
        uses: actions/checkout@v4

      - name: R telepítése
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - name: R csomagok telepítése
        run: |
          install.packages("rvest")
          install.packages("stringr")
        shell: Rscript {0}

      - name: Budapest vízállás program futtatása
        run: Rscript budapest_vizallas_06.R
